#!/bin/bash
./publish 
# to dirlt-aws.
gc && ssh dirlt-aws "./git-sync"

# to github pages.
rsync -avrzL $HOME/github/sperm/www $HOME/github/dirlt.com
cd $HOME/github/dirlt.com 
git add * && git commit -a -m 'mirror' 
git push github gh-pages
