#!/bin/bash

# do publish
# find emacs executable file.
kernel=`uname -s`
emacs="emacs"
if [ $kernel"X" = "DarwinX" ]
then
    emacs="/Applications/Emacs.app/Contents/MacOS/Emacs"
fi

$emacs --batch --script publish.el
if [ $? != 0 ]
then
    echo "publish failed"
    exit 1
fi
./addcode
cd ../www/
rm -rf images css
ln -s ../essay/images/ images
ln -s ../essay/css css
cd ../essay/
