#!/usr/bin/env bash
#Copyright (C) dirlt

java -server \
    -Xms8192m -Xmx8192m -XX:NewSize=1024m \
    -XX:+UseConcMarkSweepGC -XX:+UseParNewGC \
    -cp FastHBaseRest.jar \
    -Dcom.sun.management.jmxremote.port=12346 \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    com.dirlt.java.FastHBaseRest.RestServer \
    --port=12345 \
    --backlog=128 \
    --hbase-quorum-spec=dp30:2181,dp20:2181,dp10:2181,dp5:2181,dp40:2181 \
    --cache-expire-time=1200 \
    --cache-max-capacity=2097152 \
    --accept-io-thread-number=4 \
    --accept-io-queue-size=16 \
    --cpu-thread-number=1024 \
    --cpu-queue-size=4096 \
    --io-thread-number=32 \
    --io-queue-size=4096 \
    --timeout=4000 \
    --debug=false \
    --close-on-failure=true \
    --kv=appuserstat.date.addHashCodeAsRowKeyPrefix:2013-07-02 \
    --kv=reboot-ratio-threshold:0.005 \
    $@
