#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

import md5

def imei2umid(imei):
    s = md5.new(imei).hexdigest()
    x = ''
    for i in range(0,len(s)):
        if i % 2 == 0 and s[i] == '0':
            continue
        x += s[i]
    return x

def main(args):
    for arg in args:
        print imei2umid(arg)

import sys
if __name__ == '__main__':
    main(sys.argv[1:])
    
