#!/usr/bin/env bash
#Copyright (C) dirlt

echo "patching fast-hbase-rest ..."
rsync -avrz $HOME/github/fast-hbase-rest/src/main/ $HOME/github/sperm/code/java/fast-hbase-rest/src/main/
rsync -vz $HOME/github/fast-hbase-rest/pom.xml $HOME/github/sperm/code/java/fast-hbase-rest/pom.xml
rsync -vz $HOME/github/fast-hbase-rest/run-fast-hbase-rest $HOME/github/sperm/code/java/fast-hbase-rest/run-fast-hbase-rest

echo "patching veritas ..."
rsync -avrz $HOME/github/veritas/src/main/ $HOME/github/sperm/code/java/veritas/src/main/
rsync -avrz $HOME/github/veritas/script $HOME/github/sperm/code/java/veritas/script
rsync -vz $HOME/github/veritas/pom.xml $HOME/github/sperm/code/java/veritas/pom.xml

