#!/usr/bin/env bash
#Copyright (C) dirlt

echo "patching fast-hbase-rest ..."
S="$HOME/github/fast-hbase-rest/"
D="$HOME/github/sperm/code/java/fast-hbase-rest/"

for x in src/main/ 
do
    rsync -avrz $S/$x $D/$x >/dev/null 2>&1
done

for x in pom.xml \
    .gitignore \
    run-fast-hbase-rest \
    daemon-fast-hbase-rest \
    Makefile
do
    rsync -vz $S/$x $D/$x >/dev/null 2>&1
done
