#!/bin/bash
pwd=`pwd`
if [ ! -d "$pwd/dirlt" ]
then
    echo "Are you at right backup directory???"
    exit 1
fi
    
# files.
for f in private.tar.gz
do
    echo "sync $f..."
    sudo rsync -az $HOME/$f "$pwd/dirlt/$f"
done

# dirs.
for d in doc \
    ".m2" \
    github \
    utils \
    "VirtualBox VMs" \
    vmshare
do
    echo "sync $d..."
    sudo rsync -arz "$HOME/$d/" "$pwd/dirlt/$d/"
done
