#!/bin/bash
pwd=`pwd`
# files.
for f in private.tar.gz
do
    sudo rsync -az $HOME/$f "$pwd/dirlt/$f"
done

# dirs.
for d in doc \
    ".m2" \
    github \
    utils \
    "VirtualBox VMs" \
    vmshare
do
    sudo rsync -arz "$HOME/$d/" "$pwd/dirlt/$d/"
done
