#!/usr/bin/env python
#coding:utf-8
#Copyright (C) dirlt

POM_TEMPLATE="""<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>%(groupId)s</groupId>
  <artifactId>%(artifactId)s</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>%(project)s</name>
  <url>http://dirlt.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

  <distributionManagement>    
    <repository>
      <id>releases</id>
      <name>Release Repository</name>
      <url>http://nexus:8088/nexus/content/repositories/releases/</url>
    </repository>
    <snapshotRepository>
      <id>snapshots</id>
      <name>Snapshot Repository</name>
      <url>http://nexus:8088/nexus/content/repositories/snapshots/</url>
    </snapshotRepository>
  </distributionManagement>
  
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.8.2</version>
      <scope>test</scope>
    </dependency>

    <!-- <dependency> -->
    <!--   <groupId>com.google.protobuf</groupId> -->
    <!--   <artifactId>protobuf-java</artifactId> -->
    <!--   <version>2.3.0</version> -->
    <!-- </dependency> -->
  </dependencies>
  
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>2.5.1</version>
        <configuration>
          <source>1.6</source>
          <target>1.6</target>
        </configuration>
      </plugin>    

      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <descriptorRefs>
            <descriptorRef>jar-with-dependencies</descriptorRef>
          </descriptorRefs>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id>
            <phase>package</phase>
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- <plugin> -->
      <!--   <groupId>org.codehaus.mojo</groupId> -->
      <!--   <artifactId>build-helper-maven-plugin</artifactId> -->
      <!--   <version>1.8</version> -->
      <!--   <executions> -->
      <!--     <execution> -->
      <!--       <phase>generate-sources</phase> -->
      <!--       <goals><goal>add-source</goal></goals> -->
      <!--       <configuration> -->
      <!--         <sources> -->
      <!--           <source>src/main/gen-java</source> -->
      <!--           <source>src/main/resources</source> -->
      <!--         </sources> -->
      <!--       </configuration> -->
      <!--     </execution> -->
      <!--   </executions> -->
      <!-- </plugin> -->

      <!-- <plugin> -->
      <!--   <artifactId>maven-antrun-plugin</artifactId> -->
      <!--   <executions> -->
      <!--     <execution> -->
      <!--       <id>generate-sources</id> -->
      <!--       <phase>generate-sources</phase> -->
      <!--       <configuration> -->
      <!--         <tasks> -->
      <!--           <mkdir dir="src/main/gen-java"/> -->
      <!--           <exec executable="protoc"> -->
      <!--             <arg value="src/main/proto/message.proto"/> -->
      <!--           </exec> -->
      <!--         </tasks> -->
      <!--         <sourceRoot>src/main/gen-java</sourceRoot> -->
      <!--       </configuration> -->
      <!--       <goals> -->
      <!--         <goal>run</goal> -->
      <!--       </goals> -->
      <!--     </execution> -->
      <!--   </executions> -->
      <!-- </plugin> -->
    </plugins>
  </build>

</project>
"""

LOG4J_TEMPLATE="""log.dir=.
log.file=%(artifactId)s.log

log4j.rootLogger=INFO,DRFA
#log4j.logger.%(groupId)s.%(artifactId)s=${rootLogger},console

log4j.appender.DRFA=org.apache.log4j.DailyRollingFileAppender
log4j.appender.DRFA.File=${log.dir}/${log.file}
log4j.appender.DRFA.DatePattern=.yyyy-MM-dd
log4j.appender.DRFA.layout=org.apache.log4j.PatternLayout
#log4j.appender.DRFA.layout.ConversionPattern=%%d{ISO8601} %%p %%c: %%m%%n
log4j.appender.DRFA.layout.ConversionPattern=%%d{ISO8601} %%p: %%m%%n

log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%%d{ISO8601} %%p: %%m%%n

"""


import os
def generate(project,groupId,artifactId):
    cps=groupId.split('.')
    cps.append(artifactId)
    os.system('mkdir -p %s'%(project))
    open('%s/pom.xml'%(project),'w').write(POM_TEMPLATE%(locals()))
    os.system('mkdir -p %s/src/main/java/%s/'%(project,'/'.join(cps)))
    os.system('mkdir -p %s/src/test/java/%s/'%(project,'/'.join(cps)))
    os.system('mkdir -p %s/src/main/proto/'%(project))
    os.system('mkdir -p %s/src/main/resources/'%(project))
    open('%s/src/main/resources/log4j.properties'%(project),'w').write(LOG4J_TEMPLATE%(locals()))
    os.system('mkdir -p %s/src/test/resources/'%(project))
    os.system('mkdir -p %s/config/'%(project))
    os.system('mkdir -p %s/scripts/'%(project))    

import sys
if __name__=='__main__':
    if(len(sys.argv)!=4):
        print 'create a new project in maven'
        print 'usage:%s project-name groupId artifactId'%(sys.argv[0])
    else:
        generate(sys.argv[1],sys.argv[2],sys.argv[3])
