#!/usr/bin/env bash
#Copyright (C) dirlt

java -server \
    -Xms8192m -Xmx8192m -XX:NewSize=1024m \
    -XX:+UseConcMarkSweepGC -XX:+UseParNewGC \
    -cp veritas.jar \
    -Dcom.sun.management.jmxremote.port=12348 \
    -Dcom.sun.management.jmxremote.ssl=false \
    -Dcom.sun.management.jmxremote.authenticate=false \
    com.dirlt.java.veritas.VeritasServer \
    --port=12347 \
    --backlog=128 \
    --backend-nodes=dp0:12345,dp4:12345 \
    --cpu-thread-number=1024 \
    --cpu-queue-size=4096 \
    --accept-io-thread-number=4 \
    --io-thread-number=32 \
    --timeout=300 \
    --proxy-accept-io-thread-number=4 \
    --proxy-io-thread-number=32 \
    --proxy-connection-per-node=256 \
    --proxy-connect-timeout=10 \
    --debug=false \
    --response-with-best-effort=true \
    $@

